export {
  MARKETING_NAV_HREFS,
  assertAllowedMarketingHref,
  isAllowedMarketingHref,
  isAllowedSocialHref,
  isExternalHttpHref,
  isHashHref,
  isRejectedAdminHref,
  type MarketingNavHref,
} from "./allowlist.ts";
export {
  FORBIDDEN_AVAILABLE_NOW,
  featureAvailableNowIssues,
  findForbiddenAvailableNowClaims,
  findForbiddenClaimsInText,
  forbiddenClaimsForAvailableNowField,
  packageAvailableNowIssues,
  type ForbiddenClaimHit,
} from "./claims.ts";
export {
  MARKETING_ADMIN_STATUS_LABELS,
  MARKETING_CARD_DISCLAIMER,
  assertEditorHref,
  canHideOrUnpublishNavItem,
  canRemoveNavItem,
  isProtectedNavItem,
  missingProtectedNavRoles,
  newMarketingId,
  parseMarketingHref,
  removeNavItem,
  requireMarketingHref,
  setNavItemHref,
  setNavItemVisible,
  validateMarketingEditorContent,
  type MarketingEditorIssue,
  type MarketingEditorReport,
} from "./editor.ts";
export {
  MARKETING_CMS_CONCURRENCY,
  applyMarketingMutation,
  assertMarketingAdmin,
  collectAdminHrefs,
  createSeedMarketingSnapshot,
  evaluateMarketingDocument,
  evaluatePublish,
  evaluateSaveDraft,
  isMarketingContent,
  type MarketingCmsPublishResult,
  type MarketingCmsSnapshot,
  type MarketingRevisionStatus,
} from "./document.ts";
export { findDuplicateContentSlugs } from "./editor.ts";
export {
  MARKETING_MOCK_STORAGE_KEY,
  MarketingMockStore,
  clearStoredMarketingSnapshot,
  createInitialMarketingSnapshot,
  getMarketingMockStore,
  persistMarketingMockStore,
  readStoredMarketingSnapshot,
  resetMarketingMockStoreForTests,
  snapshotHasUnpublishedChanges,
  writeStoredMarketingSnapshot,
  type MarketingMockPublishResult,
  type MarketingMockSnapshot,
  type MarketingPublishState,
} from "./mock-store.ts";
export {
  MARKETING_SEED,
} from "./seed.ts";
export {
  MARKETING_STATUS_LABELS,
  activeOf,
  collectAvailableNowText,
  getMarketingContent,
  pricingSummary,
  publishedOf,
  roadmapFeatures,
  sortByOrder,
  validateMarketingContent,
  visibleNav,
  visiblePackages,
} from "./resolve.ts";
export {
  MARKETING_ITEM_STATUSES,
  MARKETING_NAV_PLACEMENTS,
  MARKETING_PACKAGE_ICON_KEYS,
  PROTECTED_NAV_ROLES,
  type BrandContent,
  type ContactContent,
  type FaqItem,
  type FooterContent,
  type FooterLink,
  type FooterLinkGroup,
  type FooterSocial,
  type HeroContent,
  type MarketingBlogPost,
  type MarketingCaseStudy,
  type MarketingContent,
  type MarketingCta,
  type MarketingFeatureBullet,
  type MarketingItemStatus,
  type MarketingNavItem,
  type MarketingNavPlacement,
  type MarketingPackageCard,
  type MarketingPackageIconKey,
  type MarketingPartner,
  type MarketingTestimonial,
  type PackagesSectionContent,
  type PricingContent,
  type PromoBanner,
  type ProtectedNavRole,
} from "./types.ts";
