/**
 * Semantic Lucide icons for Property Setup fields.
 * Cards must not assign field icons independently.
 */
import type { LucideIcon } from "lucide-react";
import {
  BadgeCheck,
  Banknote,
  Bed,
  BedDouble,
  Bell,
  Briefcase,
  Building,
  Building2,
  CalendarDays,
  ChartColumn,
  CircleCheck,
  Clock3,
  Coins,
  Contact,
  CreditCard,
  FileText,
  Flag,
  Globe2,
  Hash,
  Image,
  Landmark,
  Languages,
  Layers,
  Link2,
  Lock,
  Mail,
  MapPin,
  Network,
  Palette,
  Phone,
  Plug,
  Receipt,
  RefreshCw,
  Rocket,
  ScrollText,
  Share2,
  Shield,
  Sparkles,
  Star,
  Tag,
  Upload,
  User,
  UserCog,
  Users,
  UtensilsCrossed,
  Wifi,
  Wrench,
  TrendingUp,
} from "lucide-react";

export const PROPERTY_SETUP_FIELD_ICONS = {
  property: Building2,
  property_type: Building2,
  room: BedDouble,
  room_type: BedDouble,
  bed: Bed,
  guest: Users,
  person: User,
  phone: Phone,
  email: Mail,
  website: Globe2,
  country: Flag,
  address: MapPin,
  currency: Coins,
  money: Banknote,
  tax: Receipt,
  document: FileText,
  date: CalendarDays,
  time: Clock3,
  timezone: Clock3,
  security: Shield,
  password: Lock,
  report: ChartColumn,
  integration: Plug,
  network: Share2,
  facility: Building,
  department: Network,
  notification: Bell,
  payment: CreditCard,
  hash: Hash,
  briefcase: Briefcase,
  star: Star,
  language: Languages,
  tag: Tag,
  badge: BadgeCheck,
  image: Image,
  palette: Palette,
  landmark: Landmark,
  contact: Contact,
  amenity: Sparkles,
  housekeeping: Sparkles,
  inventory: Layers,
  maintenance: Wrench,
  meal: UtensilsCrossed,
  revenue: TrendingUp,
  service: Bell,
  role: UserCog,
  audit: ScrollText,
  import: Upload,
  offline: Wifi,
  sync: RefreshCw,
  validation: CircleCheck,
  activation: Rocket,
  mapping: Link2,
  event: CalendarDays,
} as const satisfies Record<string, LucideIcon>;

export type PropertySetupFieldIconKey = keyof typeof PROPERTY_SETUP_FIELD_ICONS;

export function propertySetupFieldIcon(key: PropertySetupFieldIconKey): LucideIcon {
  return PROPERTY_SETUP_FIELD_ICONS[key];
}
