/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TableRouteImport } from './routes/table'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as KitchenIndexRouteImport } from './routes/kitchen/index'
import { Route as KitchenLoginRouteImport } from './routes/kitchen/login'
import { Route as RestaurantDashboardRouteImport } from './routes/restaurant/dashboard'
import { Route as RestaurantLoginRouteImport } from './routes/restaurant/login'
import { Route as RestaurantRegisterRouteImport } from './routes/restaurant/register'
import { Route as RestaurantSettingsRouteImport } from './routes/restaurant/settings'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const KitchenIndexRoute = KitchenIndexRouteImport.update({
  id: '/kitchen/',
  path: '/kitchen/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenLoginRoute = KitchenLoginRouteImport.update({
  id: '/kitchen/login',
  path: '/kitchen/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantDashboardRoute = RestaurantDashboardRouteImport.update({
  id: '/restaurant/dashboard',
  path: '/restaurant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantLoginRoute = RestaurantLoginRouteImport.update({
  id: '/restaurant/login',
  path: '/restaurant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRegisterRoute = RestaurantRegisterRouteImport.update({
  id: '/restaurant/register',
  path: '/restaurant/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSettingsRoute = RestaurantSettingsRouteImport.update({
  id: '/restaurant/settings',
  path: '/restaurant/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/confirmation': typeof ConfirmationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/status': typeof StatusRoute
  '/table': typeof TableRoute
  '/kitchen/login': typeof KitchenLoginRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/login': typeof RestaurantLoginRoute
  '/restaurant/register': typeof RestaurantRegisterRoute
  '/restaurant/settings': typeof RestaurantSettingsRoute
  '/account/': typeof AccountIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/confirmation': typeof ConfirmationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/status': typeof StatusRoute
  '/table': typeof TableRoute
  '/kitchen/login': typeof KitchenLoginRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/login': typeof RestaurantLoginRoute
  '/restaurant/register': typeof RestaurantRegisterRoute
  '/restaurant/settings': typeof RestaurantSettingsRoute
  '/account': typeof AccountIndexRoute
  '/kitchen': typeof KitchenIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/confirmation': typeof ConfirmationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/status': typeof StatusRoute
  '/table': typeof TableRoute
  '/kitchen/login': typeof KitchenLoginRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/login': typeof RestaurantLoginRoute
  '/restaurant/register': typeof RestaurantRegisterRoute
  '/restaurant/settings': typeof RestaurantSettingsRoute
  '/account/': typeof AccountIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/confirmation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/status'
    | '/table'
    | '/kitchen/login'
    | '/restaurant/dashboard'
    | '/restaurant/login'
    | '/restaurant/register'
    | '/restaurant/settings'
    | '/account/'
    | '/kitchen/'
    | '/account/orders/$orderId'
    | '/account/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/confirmation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/status'
    | '/table'
    | '/kitchen/login'
    | '/restaurant/dashboard'
    | '/restaurant/login'
    | '/restaurant/register'
    | '/restaurant/settings'
    | '/account'
    | '/kitchen'
    | '/account/orders/$orderId'
    | '/account/orders'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/confirmation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/status'
    | '/table'
    | '/kitchen/login'
    | '/restaurant/dashboard'
    | '/restaurant/login'
    | '/restaurant/register'
    | '/restaurant/settings'
    | '/account/'
    | '/kitchen/'
    | '/account/orders/$orderId'
    | '/account/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  CartRoute: typeof CartRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRoute
  StatusRoute: typeof StatusRoute
  TableRoute: typeof TableRoute
  KitchenLoginRoute: typeof KitchenLoginRoute
  RestaurantDashboardRoute: typeof RestaurantDashboardRoute
  RestaurantLoginRoute: typeof RestaurantLoginRoute
  RestaurantRegisterRoute: typeof RestaurantRegisterRoute
  RestaurantSettingsRoute: typeof RestaurantSettingsRoute
  KitchenIndexRoute: typeof KitchenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/kitchen/': {
      id: '/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof KitchenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen/login': {
      id: '/kitchen/login'
      path: '/kitchen/login'
      fullPath: '/kitchen/login'
      preLoaderRoute: typeof KitchenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/dashboard': {
      id: '/restaurant/dashboard'
      path: '/restaurant/dashboard'
      fullPath: '/restaurant/dashboard'
      preLoaderRoute: typeof RestaurantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/login': {
      id: '/restaurant/login'
      path: '/restaurant/login'
      fullPath: '/restaurant/login'
      preLoaderRoute: typeof RestaurantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/register': {
      id: '/restaurant/register'
      path: '/restaurant/register'
      fullPath: '/restaurant/register'
      preLoaderRoute: typeof RestaurantRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/settings': {
      id: '/restaurant/settings'
      path: '/restaurant/settings'
      fullPath: '/restaurant/settings'
      preLoaderRoute: typeof RestaurantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRouteRoute
    }
  }
}

interface AccountRouteRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  CartRoute: CartRoute,
  ConfirmationRoute: ConfirmationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRoute,
  StatusRoute: StatusRoute,
  TableRoute: TableRoute,
  KitchenLoginRoute: KitchenLoginRoute,
  RestaurantDashboardRoute: RestaurantDashboardRoute,
  RestaurantLoginRoute: RestaurantLoginRoute,
  RestaurantRegisterRoute: RestaurantRegisterRoute,
  RestaurantSettingsRoute: RestaurantSettingsRoute,
  KitchenIndexRoute: KitchenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
