/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteRouteImport } from './routes/account/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TableRouteImport } from './routes/table'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as KitchenIndexRouteImport } from './routes/kitchen/index'
import { Route as KitchenLoginRouteImport } from './routes/kitchen/login'
import { Route as RRestaurantSlugRouteRouteImport } from './routes/r/$restaurantSlug/route'
import { Route as RestaurantDashboardRouteImport } from './routes/restaurant/dashboard'
import { Route as RestaurantHomeRouteImport } from './routes/restaurant/home'
import { Route as RestaurantKitchenRouteImport } from './routes/restaurant/kitchen'
import { Route as RestaurantLoginRouteImport } from './routes/restaurant/login'
import { Route as RestaurantMenuRouteImport } from './routes/restaurant/menu'
import { Route as RestaurantRegisterRouteImport } from './routes/restaurant/register'
import { Route as RestaurantSettingsRouteImport } from './routes/restaurant/settings'
import { Route as RestaurantStaffRouteImport } from './routes/restaurant/staff'
import { Route as RestaurantTablesRouteImport } from './routes/restaurant/tables'
import { Route as RestaurantWaiterRouteImport } from './routes/restaurant/waiter'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders/index'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders/$orderId'
import { Route as AdminRestaurantsIndexRouteImport } from './routes/admin/restaurants/index'
import { Route as AdminRestaurantsRestaurantIdRouteImport } from './routes/admin/restaurants/$restaurantId'
import { Route as RRestaurantSlugIndexRouteImport } from './routes/r/$restaurantSlug/index'
import { Route as RRestaurantSlugCartRouteImport } from './routes/r/$restaurantSlug/cart'
import { Route as RRestaurantSlugConfirmationRouteImport } from './routes/r/$restaurantSlug/confirmation'
import { Route as RRestaurantSlugReviewRouteImport } from './routes/r/$restaurantSlug/review'
import { Route as RRestaurantSlugStatusRouteImport } from './routes/r/$restaurantSlug/status'
import { Route as RRestaurantSlugTableRouteImport } from './routes/r/$restaurantSlug/table'
import { Route as RestaurantBookingsIndexRouteImport } from './routes/restaurant/bookings/index'
import { Route as RestaurantBookingsReservationIdRouteImport } from './routes/restaurant/bookings/$reservationId'
import { Route as RestaurantBookingsNewRouteImport } from './routes/restaurant/bookings/new'
import { Route as RestaurantBookingsRatesRouteImport } from './routes/restaurant/bookings/rates'
import { Route as RestaurantBookingsReservationsRouteImport } from './routes/restaurant/bookings/reservations'
import { Route as RestaurantCashieringIndexRouteImport } from './routes/restaurant/cashiering/index'
import { Route as RestaurantGuestsIndexRouteImport } from './routes/restaurant/guests/index'
import { Route as RestaurantGuestsGuestIdRouteImport } from './routes/restaurant/guests/$guestId'
import { Route as RestaurantHousekeepingIndexRouteImport } from './routes/restaurant/housekeeping/index'
import { Route as RestaurantInventoryIndexRouteImport } from './routes/restaurant/inventory/index'
import { Route as RestaurantOrdersIndexRouteImport } from './routes/restaurant/orders/index'
import { Route as RestaurantOrdersOrderIdRouteImport } from './routes/restaurant/orders/$orderId'
import { Route as RestaurantRoomsIndexRouteImport } from './routes/restaurant/rooms/index'
import { Route as RestaurantRoomsArrivalsRouteImport } from './routes/restaurant/rooms/arrivals'
import { Route as RestaurantRoomsDeparturesRouteImport } from './routes/restaurant/rooms/departures'
import { Route as RestaurantRoomsInHouseRouteImport } from './routes/restaurant/rooms/in-house'
import { Route as RRestaurantSlugOrderOrderIdRouteImport } from './routes/r/$restaurantSlug/order/$orderId'
import { Route as RRestaurantSlugTQrTokenRouteImport } from './routes/r/$restaurantSlug/t/$qrToken'
import { Route as RestaurantCashieringFoliosFolioIdRouteImport } from './routes/restaurant/cashiering/folios/$folioId'
import { Route as RestaurantCashieringNightAuditIndexRouteImport } from './routes/restaurant/cashiering/night-audit/index'
import { Route as RestaurantCashieringNightAuditRunIdRouteImport } from './routes/restaurant/cashiering/night-audit/$runId'
import { Route as RestaurantInventoryPurchasingPurchaseOrderIdRouteImport } from './routes/restaurant/inventory/purchasing/$purchaseOrderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRouteRoute = AccountRouteRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TableRoute = TableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenIndexRoute = KitchenIndexRouteImport.update({
  id: '/kitchen/',
  path: '/kitchen/',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenLoginRoute = KitchenLoginRouteImport.update({
  id: '/kitchen/login',
  path: '/kitchen/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RRestaurantSlugRouteRoute = RRestaurantSlugRouteRouteImport.update({
  id: '/r/$restaurantSlug',
  path: '/r/$restaurantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantDashboardRoute = RestaurantDashboardRouteImport.update({
  id: '/restaurant/dashboard',
  path: '/restaurant/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantHomeRoute = RestaurantHomeRouteImport.update({
  id: '/restaurant/home',
  path: '/restaurant/home',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantKitchenRoute = RestaurantKitchenRouteImport.update({
  id: '/restaurant/kitchen',
  path: '/restaurant/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantLoginRoute = RestaurantLoginRouteImport.update({
  id: '/restaurant/login',
  path: '/restaurant/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantMenuRoute = RestaurantMenuRouteImport.update({
  id: '/restaurant/menu',
  path: '/restaurant/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRegisterRoute = RestaurantRegisterRouteImport.update({
  id: '/restaurant/register',
  path: '/restaurant/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantSettingsRoute = RestaurantSettingsRouteImport.update({
  id: '/restaurant/settings',
  path: '/restaurant/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantStaffRoute = RestaurantStaffRouteImport.update({
  id: '/restaurant/staff',
  path: '/restaurant/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantTablesRoute = RestaurantTablesRouteImport.update({
  id: '/restaurant/tables',
  path: '/restaurant/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantWaiterRoute = RestaurantWaiterRouteImport.update({
  id: '/restaurant/waiter',
  path: '/restaurant/waiter',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AccountRouteRoute,
} as any)
const AdminRestaurantsIndexRoute = AdminRestaurantsIndexRouteImport.update({
  id: '/admin/restaurants/',
  path: '/admin/restaurants/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsRestaurantIdRoute =
  AdminRestaurantsRestaurantIdRouteImport.update({
    id: '/admin/restaurants/$restaurantId',
    path: '/admin/restaurants/$restaurantId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RRestaurantSlugIndexRoute = RRestaurantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RRestaurantSlugRouteRoute,
} as any)
const RRestaurantSlugCartRoute = RRestaurantSlugCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => RRestaurantSlugRouteRoute,
} as any)
const RRestaurantSlugConfirmationRoute =
  RRestaurantSlugConfirmationRouteImport.update({
    id: '/confirmation',
    path: '/confirmation',
    getParentRoute: () => RRestaurantSlugRouteRoute,
  } as any)
const RRestaurantSlugReviewRoute = RRestaurantSlugReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => RRestaurantSlugRouteRoute,
} as any)
const RRestaurantSlugStatusRoute = RRestaurantSlugStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => RRestaurantSlugRouteRoute,
} as any)
const RRestaurantSlugTableRoute = RRestaurantSlugTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => RRestaurantSlugRouteRoute,
} as any)
const RestaurantBookingsIndexRoute = RestaurantBookingsIndexRouteImport.update({
  id: '/restaurant/bookings/',
  path: '/restaurant/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantBookingsReservationIdRoute =
  RestaurantBookingsReservationIdRouteImport.update({
    id: '/restaurant/bookings/$reservationId',
    path: '/restaurant/bookings/$reservationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantBookingsNewRoute = RestaurantBookingsNewRouteImport.update({
  id: '/restaurant/bookings/new',
  path: '/restaurant/bookings/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantBookingsRatesRoute = RestaurantBookingsRatesRouteImport.update({
  id: '/restaurant/bookings/rates',
  path: '/restaurant/bookings/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantBookingsReservationsRoute =
  RestaurantBookingsReservationsRouteImport.update({
    id: '/restaurant/bookings/reservations',
    path: '/restaurant/bookings/reservations',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantCashieringIndexRoute =
  RestaurantCashieringIndexRouteImport.update({
    id: '/restaurant/cashiering/',
    path: '/restaurant/cashiering/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantGuestsIndexRoute = RestaurantGuestsIndexRouteImport.update({
  id: '/restaurant/guests/',
  path: '/restaurant/guests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantGuestsGuestIdRoute = RestaurantGuestsGuestIdRouteImport.update({
  id: '/restaurant/guests/$guestId',
  path: '/restaurant/guests/$guestId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantHousekeepingIndexRoute =
  RestaurantHousekeepingIndexRouteImport.update({
    id: '/restaurant/housekeeping/',
    path: '/restaurant/housekeeping/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantInventoryIndexRoute =
  RestaurantInventoryIndexRouteImport.update({
    id: '/restaurant/inventory/',
    path: '/restaurant/inventory/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantOrdersIndexRoute = RestaurantOrdersIndexRouteImport.update({
  id: '/restaurant/orders/',
  path: '/restaurant/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantOrdersOrderIdRoute = RestaurantOrdersOrderIdRouteImport.update({
  id: '/restaurant/orders/$orderId',
  path: '/restaurant/orders/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoomsIndexRoute = RestaurantRoomsIndexRouteImport.update({
  id: '/restaurant/rooms/',
  path: '/restaurant/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoomsArrivalsRoute = RestaurantRoomsArrivalsRouteImport.update({
  id: '/restaurant/rooms/arrivals',
  path: '/restaurant/rooms/arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoomsDeparturesRoute =
  RestaurantRoomsDeparturesRouteImport.update({
    id: '/restaurant/rooms/departures',
    path: '/restaurant/rooms/departures',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantRoomsInHouseRoute = RestaurantRoomsInHouseRouteImport.update({
  id: '/restaurant/rooms/in-house',
  path: '/restaurant/rooms/in-house',
  getParentRoute: () => rootRouteImport,
} as any)
const RRestaurantSlugOrderOrderIdRoute =
  RRestaurantSlugOrderOrderIdRouteImport.update({
    id: '/order/$orderId',
    path: '/order/$orderId',
    getParentRoute: () => RRestaurantSlugRouteRoute,
  } as any)
const RRestaurantSlugTQrTokenRoute = RRestaurantSlugTQrTokenRouteImport.update({
  id: '/t/$qrToken',
  path: '/t/$qrToken',
  getParentRoute: () => RRestaurantSlugRouteRoute,
} as any)
const RestaurantCashieringFoliosFolioIdRoute =
  RestaurantCashieringFoliosFolioIdRouteImport.update({
    id: '/restaurant/cashiering/folios/$folioId',
    path: '/restaurant/cashiering/folios/$folioId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantCashieringNightAuditIndexRoute =
  RestaurantCashieringNightAuditIndexRouteImport.update({
    id: '/restaurant/cashiering/night-audit/',
    path: '/restaurant/cashiering/night-audit/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantCashieringNightAuditRunIdRoute =
  RestaurantCashieringNightAuditRunIdRouteImport.update({
    id: '/restaurant/cashiering/night-audit/$runId',
    path: '/restaurant/cashiering/night-audit/$runId',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurantInventoryPurchasingPurchaseOrderIdRoute =
  RestaurantInventoryPurchasingPurchaseOrderIdRouteImport.update({
    id: '/restaurant/inventory/purchasing/$purchaseOrderId',
    path: '/restaurant/inventory/purchasing/$purchaseOrderId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/confirmation': typeof ConfirmationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/scan': typeof ScanRoute
  '/status': typeof StatusRoute
  '/table': typeof TableRoute
  '/r/$restaurantSlug': typeof RRestaurantSlugRouteRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/kitchen/login': typeof KitchenLoginRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/home': typeof RestaurantHomeRoute
  '/restaurant/kitchen': typeof RestaurantKitchenRoute
  '/restaurant/login': typeof RestaurantLoginRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/register': typeof RestaurantRegisterRoute
  '/restaurant/settings': typeof RestaurantSettingsRoute
  '/restaurant/staff': typeof RestaurantStaffRoute
  '/restaurant/tables': typeof RestaurantTablesRoute
  '/restaurant/waiter': typeof RestaurantWaiterRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/restaurants/$restaurantId': typeof AdminRestaurantsRestaurantIdRoute
  '/r/$restaurantSlug/cart': typeof RRestaurantSlugCartRoute
  '/r/$restaurantSlug/confirmation': typeof RRestaurantSlugConfirmationRoute
  '/r/$restaurantSlug/review': typeof RRestaurantSlugReviewRoute
  '/r/$restaurantSlug/status': typeof RRestaurantSlugStatusRoute
  '/r/$restaurantSlug/table': typeof RRestaurantSlugTableRoute
  '/restaurant/bookings/$reservationId': typeof RestaurantBookingsReservationIdRoute
  '/restaurant/bookings/new': typeof RestaurantBookingsNewRoute
  '/restaurant/bookings/rates': typeof RestaurantBookingsRatesRoute
  '/restaurant/bookings/reservations': typeof RestaurantBookingsReservationsRoute
  '/restaurant/guests/$guestId': typeof RestaurantGuestsGuestIdRoute
  '/restaurant/orders/$orderId': typeof RestaurantOrdersOrderIdRoute
  '/restaurant/rooms/arrivals': typeof RestaurantRoomsArrivalsRoute
  '/restaurant/rooms/departures': typeof RestaurantRoomsDeparturesRoute
  '/restaurant/rooms/in-house': typeof RestaurantRoomsInHouseRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/restaurants/': typeof AdminRestaurantsIndexRoute
  '/r/$restaurantSlug/': typeof RRestaurantSlugIndexRoute
  '/restaurant/bookings/': typeof RestaurantBookingsIndexRoute
  '/restaurant/cashiering/': typeof RestaurantCashieringIndexRoute
  '/restaurant/guests/': typeof RestaurantGuestsIndexRoute
  '/restaurant/housekeeping/': typeof RestaurantHousekeepingIndexRoute
  '/restaurant/inventory/': typeof RestaurantInventoryIndexRoute
  '/restaurant/orders/': typeof RestaurantOrdersIndexRoute
  '/restaurant/rooms/': typeof RestaurantRoomsIndexRoute
  '/r/$restaurantSlug/order/$orderId': typeof RRestaurantSlugOrderOrderIdRoute
  '/r/$restaurantSlug/t/$qrToken': typeof RRestaurantSlugTQrTokenRoute
  '/restaurant/cashiering/folios/$folioId': typeof RestaurantCashieringFoliosFolioIdRoute
  '/restaurant/cashiering/night-audit/$runId': typeof RestaurantCashieringNightAuditRunIdRoute
  '/restaurant/inventory/purchasing/$purchaseOrderId': typeof RestaurantInventoryPurchasingPurchaseOrderIdRoute
  '/restaurant/cashiering/night-audit/': typeof RestaurantCashieringNightAuditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/confirmation': typeof ConfirmationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/scan': typeof ScanRoute
  '/status': typeof StatusRoute
  '/table': typeof TableRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/kitchen/login': typeof KitchenLoginRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/home': typeof RestaurantHomeRoute
  '/restaurant/kitchen': typeof RestaurantKitchenRoute
  '/restaurant/login': typeof RestaurantLoginRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/register': typeof RestaurantRegisterRoute
  '/restaurant/settings': typeof RestaurantSettingsRoute
  '/restaurant/staff': typeof RestaurantStaffRoute
  '/restaurant/tables': typeof RestaurantTablesRoute
  '/restaurant/waiter': typeof RestaurantWaiterRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/kitchen': typeof KitchenIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/restaurants/$restaurantId': typeof AdminRestaurantsRestaurantIdRoute
  '/r/$restaurantSlug/cart': typeof RRestaurantSlugCartRoute
  '/r/$restaurantSlug/confirmation': typeof RRestaurantSlugConfirmationRoute
  '/r/$restaurantSlug/review': typeof RRestaurantSlugReviewRoute
  '/r/$restaurantSlug/status': typeof RRestaurantSlugStatusRoute
  '/r/$restaurantSlug/table': typeof RRestaurantSlugTableRoute
  '/restaurant/bookings/$reservationId': typeof RestaurantBookingsReservationIdRoute
  '/restaurant/bookings/new': typeof RestaurantBookingsNewRoute
  '/restaurant/bookings/rates': typeof RestaurantBookingsRatesRoute
  '/restaurant/bookings/reservations': typeof RestaurantBookingsReservationsRoute
  '/restaurant/guests/$guestId': typeof RestaurantGuestsGuestIdRoute
  '/restaurant/orders/$orderId': typeof RestaurantOrdersOrderIdRoute
  '/restaurant/rooms/arrivals': typeof RestaurantRoomsArrivalsRoute
  '/restaurant/rooms/departures': typeof RestaurantRoomsDeparturesRoute
  '/restaurant/rooms/in-house': typeof RestaurantRoomsInHouseRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/restaurants': typeof AdminRestaurantsIndexRoute
  '/r/$restaurantSlug': typeof RRestaurantSlugIndexRoute
  '/restaurant/bookings': typeof RestaurantBookingsIndexRoute
  '/restaurant/cashiering': typeof RestaurantCashieringIndexRoute
  '/restaurant/guests': typeof RestaurantGuestsIndexRoute
  '/restaurant/housekeeping': typeof RestaurantHousekeepingIndexRoute
  '/restaurant/inventory': typeof RestaurantInventoryIndexRoute
  '/restaurant/orders': typeof RestaurantOrdersIndexRoute
  '/restaurant/rooms': typeof RestaurantRoomsIndexRoute
  '/r/$restaurantSlug/order/$orderId': typeof RRestaurantSlugOrderOrderIdRoute
  '/r/$restaurantSlug/t/$qrToken': typeof RRestaurantSlugTQrTokenRoute
  '/restaurant/cashiering/folios/$folioId': typeof RestaurantCashieringFoliosFolioIdRoute
  '/restaurant/cashiering/night-audit/$runId': typeof RestaurantCashieringNightAuditRunIdRoute
  '/restaurant/inventory/purchasing/$purchaseOrderId': typeof RestaurantInventoryPurchasingPurchaseOrderIdRoute
  '/restaurant/cashiering/night-audit': typeof RestaurantCashieringNightAuditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/confirmation': typeof ConfirmationRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/review': typeof ReviewRoute
  '/scan': typeof ScanRoute
  '/status': typeof StatusRoute
  '/table': typeof TableRoute
  '/r/$restaurantSlug': typeof RRestaurantSlugRouteRouteWithChildren
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/kitchen/login': typeof KitchenLoginRoute
  '/restaurant/dashboard': typeof RestaurantDashboardRoute
  '/restaurant/home': typeof RestaurantHomeRoute
  '/restaurant/kitchen': typeof RestaurantKitchenRoute
  '/restaurant/login': typeof RestaurantLoginRoute
  '/restaurant/menu': typeof RestaurantMenuRoute
  '/restaurant/register': typeof RestaurantRegisterRoute
  '/restaurant/settings': typeof RestaurantSettingsRoute
  '/restaurant/staff': typeof RestaurantStaffRoute
  '/restaurant/tables': typeof RestaurantTablesRoute
  '/restaurant/waiter': typeof RestaurantWaiterRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/kitchen/': typeof KitchenIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/restaurants/$restaurantId': typeof AdminRestaurantsRestaurantIdRoute
  '/r/$restaurantSlug/cart': typeof RRestaurantSlugCartRoute
  '/r/$restaurantSlug/confirmation': typeof RRestaurantSlugConfirmationRoute
  '/r/$restaurantSlug/review': typeof RRestaurantSlugReviewRoute
  '/r/$restaurantSlug/status': typeof RRestaurantSlugStatusRoute
  '/r/$restaurantSlug/table': typeof RRestaurantSlugTableRoute
  '/restaurant/bookings/$reservationId': typeof RestaurantBookingsReservationIdRoute
  '/restaurant/bookings/new': typeof RestaurantBookingsNewRoute
  '/restaurant/bookings/rates': typeof RestaurantBookingsRatesRoute
  '/restaurant/bookings/reservations': typeof RestaurantBookingsReservationsRoute
  '/restaurant/guests/$guestId': typeof RestaurantGuestsGuestIdRoute
  '/restaurant/orders/$orderId': typeof RestaurantOrdersOrderIdRoute
  '/restaurant/rooms/arrivals': typeof RestaurantRoomsArrivalsRoute
  '/restaurant/rooms/departures': typeof RestaurantRoomsDeparturesRoute
  '/restaurant/rooms/in-house': typeof RestaurantRoomsInHouseRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/restaurants/': typeof AdminRestaurantsIndexRoute
  '/r/$restaurantSlug/': typeof RRestaurantSlugIndexRoute
  '/restaurant/bookings/': typeof RestaurantBookingsIndexRoute
  '/restaurant/cashiering/': typeof RestaurantCashieringIndexRoute
  '/restaurant/guests/': typeof RestaurantGuestsIndexRoute
  '/restaurant/housekeeping/': typeof RestaurantHousekeepingIndexRoute
  '/restaurant/inventory/': typeof RestaurantInventoryIndexRoute
  '/restaurant/orders/': typeof RestaurantOrdersIndexRoute
  '/restaurant/rooms/': typeof RestaurantRoomsIndexRoute
  '/r/$restaurantSlug/order/$orderId': typeof RRestaurantSlugOrderOrderIdRoute
  '/r/$restaurantSlug/t/$qrToken': typeof RRestaurantSlugTQrTokenRoute
  '/restaurant/cashiering/folios/$folioId': typeof RestaurantCashieringFoliosFolioIdRoute
  '/restaurant/cashiering/night-audit/$runId': typeof RestaurantCashieringNightAuditRunIdRoute
  '/restaurant/inventory/purchasing/$purchaseOrderId': typeof RestaurantInventoryPurchasingPurchaseOrderIdRoute
  '/restaurant/cashiering/night-audit/': typeof RestaurantCashieringNightAuditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/cart'
    | '/confirmation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/scan'
    | '/status'
    | '/table'
    | '/r/$restaurantSlug'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/settings'
    | '/kitchen/login'
    | '/restaurant/dashboard'
    | '/restaurant/home'
    | '/restaurant/kitchen'
    | '/restaurant/login'
    | '/restaurant/menu'
    | '/restaurant/register'
    | '/restaurant/settings'
    | '/restaurant/staff'
    | '/restaurant/tables'
    | '/restaurant/waiter'
    | '/account/'
    | '/admin/'
    | '/kitchen/'
    | '/account/orders/$orderId'
    | '/admin/restaurants/$restaurantId'
    | '/r/$restaurantSlug/cart'
    | '/r/$restaurantSlug/confirmation'
    | '/r/$restaurantSlug/review'
    | '/r/$restaurantSlug/status'
    | '/r/$restaurantSlug/table'
    | '/restaurant/bookings/$reservationId'
    | '/restaurant/bookings/new'
    | '/restaurant/bookings/rates'
    | '/restaurant/bookings/reservations'
    | '/restaurant/guests/$guestId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/rooms/arrivals'
    | '/restaurant/rooms/departures'
    | '/restaurant/rooms/in-house'
    | '/account/orders/'
    | '/admin/restaurants/'
    | '/r/$restaurantSlug/'
    | '/restaurant/bookings/'
    | '/restaurant/cashiering/'
    | '/restaurant/guests/'
    | '/restaurant/housekeeping/'
    | '/restaurant/inventory/'
    | '/restaurant/orders/'
    | '/restaurant/rooms/'
    | '/r/$restaurantSlug/order/$orderId'
    | '/r/$restaurantSlug/t/$qrToken'
    | '/restaurant/cashiering/folios/$folioId'
    | '/restaurant/cashiering/night-audit/$runId'
    | '/restaurant/inventory/purchasing/$purchaseOrderId'
    | '/restaurant/cashiering/night-audit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/confirmation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/scan'
    | '/status'
    | '/table'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/settings'
    | '/kitchen/login'
    | '/restaurant/dashboard'
    | '/restaurant/home'
    | '/restaurant/kitchen'
    | '/restaurant/login'
    | '/restaurant/menu'
    | '/restaurant/register'
    | '/restaurant/settings'
    | '/restaurant/staff'
    | '/restaurant/tables'
    | '/restaurant/waiter'
    | '/account'
    | '/admin'
    | '/kitchen'
    | '/account/orders/$orderId'
    | '/admin/restaurants/$restaurantId'
    | '/r/$restaurantSlug/cart'
    | '/r/$restaurantSlug/confirmation'
    | '/r/$restaurantSlug/review'
    | '/r/$restaurantSlug/status'
    | '/r/$restaurantSlug/table'
    | '/restaurant/bookings/$reservationId'
    | '/restaurant/bookings/new'
    | '/restaurant/bookings/rates'
    | '/restaurant/bookings/reservations'
    | '/restaurant/guests/$guestId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/rooms/arrivals'
    | '/restaurant/rooms/departures'
    | '/restaurant/rooms/in-house'
    | '/account/orders'
    | '/admin/restaurants'
    | '/r/$restaurantSlug'
    | '/restaurant/bookings'
    | '/restaurant/cashiering'
    | '/restaurant/guests'
    | '/restaurant/housekeeping'
    | '/restaurant/inventory'
    | '/restaurant/orders'
    | '/restaurant/rooms'
    | '/r/$restaurantSlug/order/$orderId'
    | '/r/$restaurantSlug/t/$qrToken'
    | '/restaurant/cashiering/folios/$folioId'
    | '/restaurant/cashiering/night-audit/$runId'
    | '/restaurant/inventory/purchasing/$purchaseOrderId'
    | '/restaurant/cashiering/night-audit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/cart'
    | '/confirmation'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/review'
    | '/scan'
    | '/status'
    | '/table'
    | '/r/$restaurantSlug'
    | '/admin/customers'
    | '/admin/login'
    | '/admin/settings'
    | '/kitchen/login'
    | '/restaurant/dashboard'
    | '/restaurant/home'
    | '/restaurant/kitchen'
    | '/restaurant/login'
    | '/restaurant/menu'
    | '/restaurant/register'
    | '/restaurant/settings'
    | '/restaurant/staff'
    | '/restaurant/tables'
    | '/restaurant/waiter'
    | '/account/'
    | '/admin/'
    | '/kitchen/'
    | '/account/orders/$orderId'
    | '/admin/restaurants/$restaurantId'
    | '/r/$restaurantSlug/cart'
    | '/r/$restaurantSlug/confirmation'
    | '/r/$restaurantSlug/review'
    | '/r/$restaurantSlug/status'
    | '/r/$restaurantSlug/table'
    | '/restaurant/bookings/$reservationId'
    | '/restaurant/bookings/new'
    | '/restaurant/bookings/rates'
    | '/restaurant/bookings/reservations'
    | '/restaurant/guests/$guestId'
    | '/restaurant/orders/$orderId'
    | '/restaurant/rooms/arrivals'
    | '/restaurant/rooms/departures'
    | '/restaurant/rooms/in-house'
    | '/account/orders/'
    | '/admin/restaurants/'
    | '/r/$restaurantSlug/'
    | '/restaurant/bookings/'
    | '/restaurant/cashiering/'
    | '/restaurant/guests/'
    | '/restaurant/housekeeping/'
    | '/restaurant/inventory/'
    | '/restaurant/orders/'
    | '/restaurant/rooms/'
    | '/r/$restaurantSlug/order/$orderId'
    | '/r/$restaurantSlug/t/$qrToken'
    | '/restaurant/cashiering/folios/$folioId'
    | '/restaurant/cashiering/night-audit/$runId'
    | '/restaurant/inventory/purchasing/$purchaseOrderId'
    | '/restaurant/cashiering/night-audit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRouteRoute: typeof AccountRouteRouteWithChildren
  CartRoute: typeof CartRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewRoute: typeof ReviewRoute
  ScanRoute: typeof ScanRoute
  StatusRoute: typeof StatusRoute
  TableRoute: typeof TableRoute
  RRestaurantSlugRouteRoute: typeof RRestaurantSlugRouteRouteWithChildren
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  KitchenLoginRoute: typeof KitchenLoginRoute
  RestaurantDashboardRoute: typeof RestaurantDashboardRoute
  RestaurantHomeRoute: typeof RestaurantHomeRoute
  RestaurantKitchenRoute: typeof RestaurantKitchenRoute
  RestaurantLoginRoute: typeof RestaurantLoginRoute
  RestaurantMenuRoute: typeof RestaurantMenuRoute
  RestaurantRegisterRoute: typeof RestaurantRegisterRoute
  RestaurantSettingsRoute: typeof RestaurantSettingsRoute
  RestaurantStaffRoute: typeof RestaurantStaffRoute
  RestaurantTablesRoute: typeof RestaurantTablesRoute
  RestaurantWaiterRoute: typeof RestaurantWaiterRoute
  AdminIndexRoute: typeof AdminIndexRoute
  KitchenIndexRoute: typeof KitchenIndexRoute
  AdminRestaurantsRestaurantIdRoute: typeof AdminRestaurantsRestaurantIdRoute
  RestaurantBookingsReservationIdRoute: typeof RestaurantBookingsReservationIdRoute
  RestaurantBookingsNewRoute: typeof RestaurantBookingsNewRoute
  RestaurantBookingsRatesRoute: typeof RestaurantBookingsRatesRoute
  RestaurantBookingsReservationsRoute: typeof RestaurantBookingsReservationsRoute
  RestaurantGuestsGuestIdRoute: typeof RestaurantGuestsGuestIdRoute
  RestaurantOrdersOrderIdRoute: typeof RestaurantOrdersOrderIdRoute
  RestaurantRoomsArrivalsRoute: typeof RestaurantRoomsArrivalsRoute
  RestaurantRoomsDeparturesRoute: typeof RestaurantRoomsDeparturesRoute
  RestaurantRoomsInHouseRoute: typeof RestaurantRoomsInHouseRoute
  AdminRestaurantsIndexRoute: typeof AdminRestaurantsIndexRoute
  RestaurantBookingsIndexRoute: typeof RestaurantBookingsIndexRoute
  RestaurantCashieringIndexRoute: typeof RestaurantCashieringIndexRoute
  RestaurantGuestsIndexRoute: typeof RestaurantGuestsIndexRoute
  RestaurantHousekeepingIndexRoute: typeof RestaurantHousekeepingIndexRoute
  RestaurantInventoryIndexRoute: typeof RestaurantInventoryIndexRoute
  RestaurantOrdersIndexRoute: typeof RestaurantOrdersIndexRoute
  RestaurantRoomsIndexRoute: typeof RestaurantRoomsIndexRoute
  RestaurantCashieringFoliosFolioIdRoute: typeof RestaurantCashieringFoliosFolioIdRoute
  RestaurantCashieringNightAuditRunIdRoute: typeof RestaurantCashieringNightAuditRunIdRoute
  RestaurantInventoryPurchasingPurchaseOrderIdRoute: typeof RestaurantInventoryPurchasingPurchaseOrderIdRoute
  RestaurantCashieringNightAuditIndexRoute: typeof RestaurantCashieringNightAuditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table': {
      id: '/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof TableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen/': {
      id: '/kitchen/'
      path: '/kitchen'
      fullPath: '/kitchen/'
      preLoaderRoute: typeof KitchenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen/login': {
      id: '/kitchen/login'
      path: '/kitchen/login'
      fullPath: '/kitchen/login'
      preLoaderRoute: typeof KitchenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$restaurantSlug': {
      id: '/r/$restaurantSlug'
      path: '/r/$restaurantSlug'
      fullPath: '/r/$restaurantSlug'
      preLoaderRoute: typeof RRestaurantSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/dashboard': {
      id: '/restaurant/dashboard'
      path: '/restaurant/dashboard'
      fullPath: '/restaurant/dashboard'
      preLoaderRoute: typeof RestaurantDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/home': {
      id: '/restaurant/home'
      path: '/restaurant/home'
      fullPath: '/restaurant/home'
      preLoaderRoute: typeof RestaurantHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/kitchen': {
      id: '/restaurant/kitchen'
      path: '/restaurant/kitchen'
      fullPath: '/restaurant/kitchen'
      preLoaderRoute: typeof RestaurantKitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/login': {
      id: '/restaurant/login'
      path: '/restaurant/login'
      fullPath: '/restaurant/login'
      preLoaderRoute: typeof RestaurantLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/menu': {
      id: '/restaurant/menu'
      path: '/restaurant/menu'
      fullPath: '/restaurant/menu'
      preLoaderRoute: typeof RestaurantMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/register': {
      id: '/restaurant/register'
      path: '/restaurant/register'
      fullPath: '/restaurant/register'
      preLoaderRoute: typeof RestaurantRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/settings': {
      id: '/restaurant/settings'
      path: '/restaurant/settings'
      fullPath: '/restaurant/settings'
      preLoaderRoute: typeof RestaurantSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/staff': {
      id: '/restaurant/staff'
      path: '/restaurant/staff'
      fullPath: '/restaurant/staff'
      preLoaderRoute: typeof RestaurantStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/tables': {
      id: '/restaurant/tables'
      path: '/restaurant/tables'
      fullPath: '/restaurant/tables'
      preLoaderRoute: typeof RestaurantTablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/waiter': {
      id: '/restaurant/waiter'
      path: '/restaurant/waiter'
      fullPath: '/restaurant/waiter'
      preLoaderRoute: typeof RestaurantWaiterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/orders'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountRouteRoute
    }
    '/admin/restaurants/': {
      id: '/admin/restaurants/'
      path: '/admin/restaurants'
      fullPath: '/admin/restaurants/'
      preLoaderRoute: typeof AdminRestaurantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurants/$restaurantId': {
      id: '/admin/restaurants/$restaurantId'
      path: '/admin/restaurants/$restaurantId'
      fullPath: '/admin/restaurants/$restaurantId'
      preLoaderRoute: typeof AdminRestaurantsRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$restaurantSlug/': {
      id: '/r/$restaurantSlug/'
      path: '/'
      fullPath: '/r/$restaurantSlug/'
      preLoaderRoute: typeof RRestaurantSlugIndexRouteImport
      parentRoute: typeof RRestaurantSlugRouteRoute
    }
    '/r/$restaurantSlug/cart': {
      id: '/r/$restaurantSlug/cart'
      path: '/cart'
      fullPath: '/r/$restaurantSlug/cart'
      preLoaderRoute: typeof RRestaurantSlugCartRouteImport
      parentRoute: typeof RRestaurantSlugRouteRoute
    }
    '/r/$restaurantSlug/confirmation': {
      id: '/r/$restaurantSlug/confirmation'
      path: '/confirmation'
      fullPath: '/r/$restaurantSlug/confirmation'
      preLoaderRoute: typeof RRestaurantSlugConfirmationRouteImport
      parentRoute: typeof RRestaurantSlugRouteRoute
    }
    '/r/$restaurantSlug/review': {
      id: '/r/$restaurantSlug/review'
      path: '/review'
      fullPath: '/r/$restaurantSlug/review'
      preLoaderRoute: typeof RRestaurantSlugReviewRouteImport
      parentRoute: typeof RRestaurantSlugRouteRoute
    }
    '/r/$restaurantSlug/status': {
      id: '/r/$restaurantSlug/status'
      path: '/status'
      fullPath: '/r/$restaurantSlug/status'
      preLoaderRoute: typeof RRestaurantSlugStatusRouteImport
      parentRoute: typeof RRestaurantSlugRouteRoute
    }
    '/r/$restaurantSlug/table': {
      id: '/r/$restaurantSlug/table'
      path: '/table'
      fullPath: '/r/$restaurantSlug/table'
      preLoaderRoute: typeof RRestaurantSlugTableRouteImport
      parentRoute: typeof RRestaurantSlugRouteRoute
    }
    '/restaurant/bookings/': {
      id: '/restaurant/bookings/'
      path: '/restaurant/bookings'
      fullPath: '/restaurant/bookings/'
      preLoaderRoute: typeof RestaurantBookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/bookings/$reservationId': {
      id: '/restaurant/bookings/$reservationId'
      path: '/restaurant/bookings/$reservationId'
      fullPath: '/restaurant/bookings/$reservationId'
      preLoaderRoute: typeof RestaurantBookingsReservationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/bookings/new': {
      id: '/restaurant/bookings/new'
      path: '/restaurant/bookings/new'
      fullPath: '/restaurant/bookings/new'
      preLoaderRoute: typeof RestaurantBookingsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/bookings/rates': {
      id: '/restaurant/bookings/rates'
      path: '/restaurant/bookings/rates'
      fullPath: '/restaurant/bookings/rates'
      preLoaderRoute: typeof RestaurantBookingsRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/bookings/reservations': {
      id: '/restaurant/bookings/reservations'
      path: '/restaurant/bookings/reservations'
      fullPath: '/restaurant/bookings/reservations'
      preLoaderRoute: typeof RestaurantBookingsReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/cashiering/': {
      id: '/restaurant/cashiering/'
      path: '/restaurant/cashiering'
      fullPath: '/restaurant/cashiering/'
      preLoaderRoute: typeof RestaurantCashieringIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/guests/': {
      id: '/restaurant/guests/'
      path: '/restaurant/guests'
      fullPath: '/restaurant/guests/'
      preLoaderRoute: typeof RestaurantGuestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/guests/$guestId': {
      id: '/restaurant/guests/$guestId'
      path: '/restaurant/guests/$guestId'
      fullPath: '/restaurant/guests/$guestId'
      preLoaderRoute: typeof RestaurantGuestsGuestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/housekeeping/': {
      id: '/restaurant/housekeeping/'
      path: '/restaurant/housekeeping'
      fullPath: '/restaurant/housekeeping/'
      preLoaderRoute: typeof RestaurantHousekeepingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/inventory/': {
      id: '/restaurant/inventory/'
      path: '/restaurant/inventory'
      fullPath: '/restaurant/inventory/'
      preLoaderRoute: typeof RestaurantInventoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/orders/': {
      id: '/restaurant/orders/'
      path: '/restaurant/orders'
      fullPath: '/restaurant/orders/'
      preLoaderRoute: typeof RestaurantOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/orders/$orderId': {
      id: '/restaurant/orders/$orderId'
      path: '/restaurant/orders/$orderId'
      fullPath: '/restaurant/orders/$orderId'
      preLoaderRoute: typeof RestaurantOrdersOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/rooms/': {
      id: '/restaurant/rooms/'
      path: '/restaurant/rooms'
      fullPath: '/restaurant/rooms/'
      preLoaderRoute: typeof RestaurantRoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/rooms/arrivals': {
      id: '/restaurant/rooms/arrivals'
      path: '/restaurant/rooms/arrivals'
      fullPath: '/restaurant/rooms/arrivals'
      preLoaderRoute: typeof RestaurantRoomsArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/rooms/departures': {
      id: '/restaurant/rooms/departures'
      path: '/restaurant/rooms/departures'
      fullPath: '/restaurant/rooms/departures'
      preLoaderRoute: typeof RestaurantRoomsDeparturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/rooms/in-house': {
      id: '/restaurant/rooms/in-house'
      path: '/restaurant/rooms/in-house'
      fullPath: '/restaurant/rooms/in-house'
      preLoaderRoute: typeof RestaurantRoomsInHouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$restaurantSlug/order/$orderId': {
      id: '/r/$restaurantSlug/order/$orderId'
      path: '/order/$orderId'
      fullPath: '/r/$restaurantSlug/order/$orderId'
      preLoaderRoute: typeof RRestaurantSlugOrderOrderIdRouteImport
      parentRoute: typeof RRestaurantSlugRouteRoute
    }
    '/r/$restaurantSlug/t/$qrToken': {
      id: '/r/$restaurantSlug/t/$qrToken'
      path: '/t/$qrToken'
      fullPath: '/r/$restaurantSlug/t/$qrToken'
      preLoaderRoute: typeof RRestaurantSlugTQrTokenRouteImport
      parentRoute: typeof RRestaurantSlugRouteRoute
    }
    '/restaurant/cashiering/folios/$folioId': {
      id: '/restaurant/cashiering/folios/$folioId'
      path: '/restaurant/cashiering/folios/$folioId'
      fullPath: '/restaurant/cashiering/folios/$folioId'
      preLoaderRoute: typeof RestaurantCashieringFoliosFolioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/cashiering/night-audit/': {
      id: '/restaurant/cashiering/night-audit/'
      path: '/restaurant/cashiering/night-audit'
      fullPath: '/restaurant/cashiering/night-audit/'
      preLoaderRoute: typeof RestaurantCashieringNightAuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/cashiering/night-audit/$runId': {
      id: '/restaurant/cashiering/night-audit/$runId'
      path: '/restaurant/cashiering/night-audit/$runId'
      fullPath: '/restaurant/cashiering/night-audit/$runId'
      preLoaderRoute: typeof RestaurantCashieringNightAuditRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant/inventory/purchasing/$purchaseOrderId': {
      id: '/restaurant/inventory/purchasing/$purchaseOrderId'
      path: '/restaurant/inventory/purchasing/$purchaseOrderId'
      fullPath: '/restaurant/inventory/purchasing/$purchaseOrderId'
      preLoaderRoute: typeof RestaurantInventoryPurchasingPurchaseOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteRouteChildren {
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountRouteRouteChildren: AccountRouteRouteChildren = {
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountRouteRouteWithChildren = AccountRouteRoute._addFileChildren(
  AccountRouteRouteChildren,
)

interface RRestaurantSlugRouteRouteChildren {
  RRestaurantSlugCartRoute: typeof RRestaurantSlugCartRoute
  RRestaurantSlugConfirmationRoute: typeof RRestaurantSlugConfirmationRoute
  RRestaurantSlugReviewRoute: typeof RRestaurantSlugReviewRoute
  RRestaurantSlugStatusRoute: typeof RRestaurantSlugStatusRoute
  RRestaurantSlugTableRoute: typeof RRestaurantSlugTableRoute
  RRestaurantSlugIndexRoute: typeof RRestaurantSlugIndexRoute
  RRestaurantSlugOrderOrderIdRoute: typeof RRestaurantSlugOrderOrderIdRoute
  RRestaurantSlugTQrTokenRoute: typeof RRestaurantSlugTQrTokenRoute
}

const RRestaurantSlugRouteRouteChildren: RRestaurantSlugRouteRouteChildren = {
  RRestaurantSlugCartRoute: RRestaurantSlugCartRoute,
  RRestaurantSlugConfirmationRoute: RRestaurantSlugConfirmationRoute,
  RRestaurantSlugReviewRoute: RRestaurantSlugReviewRoute,
  RRestaurantSlugStatusRoute: RRestaurantSlugStatusRoute,
  RRestaurantSlugTableRoute: RRestaurantSlugTableRoute,
  RRestaurantSlugIndexRoute: RRestaurantSlugIndexRoute,
  RRestaurantSlugOrderOrderIdRoute: RRestaurantSlugOrderOrderIdRoute,
  RRestaurantSlugTQrTokenRoute: RRestaurantSlugTQrTokenRoute,
}

const RRestaurantSlugRouteRouteWithChildren =
  RRestaurantSlugRouteRoute._addFileChildren(RRestaurantSlugRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRouteRoute: AccountRouteRouteWithChildren,
  CartRoute: CartRoute,
  ConfirmationRoute: ConfirmationRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewRoute: ReviewRoute,
  ScanRoute: ScanRoute,
  StatusRoute: StatusRoute,
  TableRoute: TableRoute,
  RRestaurantSlugRouteRoute: RRestaurantSlugRouteRouteWithChildren,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  KitchenLoginRoute: KitchenLoginRoute,
  RestaurantDashboardRoute: RestaurantDashboardRoute,
  RestaurantHomeRoute: RestaurantHomeRoute,
  RestaurantKitchenRoute: RestaurantKitchenRoute,
  RestaurantLoginRoute: RestaurantLoginRoute,
  RestaurantMenuRoute: RestaurantMenuRoute,
  RestaurantRegisterRoute: RestaurantRegisterRoute,
  RestaurantSettingsRoute: RestaurantSettingsRoute,
  RestaurantStaffRoute: RestaurantStaffRoute,
  RestaurantTablesRoute: RestaurantTablesRoute,
  RestaurantWaiterRoute: RestaurantWaiterRoute,
  AdminIndexRoute: AdminIndexRoute,
  KitchenIndexRoute: KitchenIndexRoute,
  AdminRestaurantsRestaurantIdRoute: AdminRestaurantsRestaurantIdRoute,
  RestaurantBookingsReservationIdRoute: RestaurantBookingsReservationIdRoute,
  RestaurantBookingsNewRoute: RestaurantBookingsNewRoute,
  RestaurantBookingsRatesRoute: RestaurantBookingsRatesRoute,
  RestaurantBookingsReservationsRoute: RestaurantBookingsReservationsRoute,
  RestaurantGuestsGuestIdRoute: RestaurantGuestsGuestIdRoute,
  RestaurantOrdersOrderIdRoute: RestaurantOrdersOrderIdRoute,
  RestaurantRoomsArrivalsRoute: RestaurantRoomsArrivalsRoute,
  RestaurantRoomsDeparturesRoute: RestaurantRoomsDeparturesRoute,
  RestaurantRoomsInHouseRoute: RestaurantRoomsInHouseRoute,
  AdminRestaurantsIndexRoute: AdminRestaurantsIndexRoute,
  RestaurantBookingsIndexRoute: RestaurantBookingsIndexRoute,
  RestaurantCashieringIndexRoute: RestaurantCashieringIndexRoute,
  RestaurantGuestsIndexRoute: RestaurantGuestsIndexRoute,
  RestaurantHousekeepingIndexRoute: RestaurantHousekeepingIndexRoute,
  RestaurantInventoryIndexRoute: RestaurantInventoryIndexRoute,
  RestaurantOrdersIndexRoute: RestaurantOrdersIndexRoute,
  RestaurantRoomsIndexRoute: RestaurantRoomsIndexRoute,
  RestaurantCashieringFoliosFolioIdRoute:
    RestaurantCashieringFoliosFolioIdRoute,
  RestaurantCashieringNightAuditRunIdRoute:
    RestaurantCashieringNightAuditRunIdRoute,
  RestaurantInventoryPurchasingPurchaseOrderIdRoute:
    RestaurantInventoryPurchasingPurchaseOrderIdRoute,
  RestaurantCashieringNightAuditIndexRoute:
    RestaurantCashieringNightAuditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
